# -*- coding: utf-8 -*-

#FIX ME add more info
"""
@file calculator.py
@author Jakub Mašek xmasek19
@brief Calculator app (school project)

 Form implementation generated from reading ui file '.\calculator.ui'
 Created by: PyQt5 UI code generator 5.15.6
"""

from PyQt5 import QtCore, QtGui, QtWidgets
import re
import calcLib
import keyboard

class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(630, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(calculator.sizePolicy().hasHeightForWidth())
        calculator.setSizePolicy(sizePolicy)
        calculator.setMinimumSize(QtCore.QSize(630, 560))
        calculator.setMaximumSize(QtCore.QSize(630, 560))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        calculator.setFont(font)
        calculator.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.centralwidget = QtWidgets.QWidget(calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 200, 610, 351))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.gridLayoutWidget.setToolTip("")
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.GridNumbers = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.GridNumbers.setContentsMargins(0, 0, 0, 0)
        self.GridNumbers.setObjectName("GridNumbers")
        self.Num7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num7.sizePolicy().hasHeightForWidth())
        self.Num7.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num7.setFont(font)
        self.Num7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num7.setToolTip("")
        self.Num7.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num7.setObjectName("Num7")
        self.GridNumbers.addWidget(self.Num7, 0, 0, 1, 1)
        self.MultiplyBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MultiplyBtn.sizePolicy().hasHeightForWidth())
        self.MultiplyBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.MultiplyBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.MultiplyBtn.setFont(font)
        self.MultiplyBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MultiplyBtn.setToolTip("")
        self.MultiplyBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.MultiplyBtn.setObjectName("MultiplyBtn")
        self.GridNumbers.addWidget(self.MultiplyBtn, 0, 5, 1, 1)
        self.Num9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num9.sizePolicy().hasHeightForWidth())
        self.Num9.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num9.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num9.setFont(font)
        self.Num9.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num9.setToolTip("")
        self.Num9.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num9.setObjectName("Num9")
        self.GridNumbers.addWidget(self.Num9, 0, 2, 1, 1)
        self.Num4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num4.sizePolicy().hasHeightForWidth())
        self.Num4.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num4.setFont(font)
        self.Num4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num4.setToolTip("")
        self.Num4.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num4.setObjectName("Num4")
        self.GridNumbers.addWidget(self.Num4, 1, 0, 1, 1)
        self.Num6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num6.sizePolicy().hasHeightForWidth())
        self.Num6.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num6.setFont(font)
        self.Num6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num6.setToolTip("")
        self.Num6.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num6.setObjectName("Num6")
        self.GridNumbers.addWidget(self.Num6, 1, 2, 1, 1)
        self.Num1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Num1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num1.sizePolicy().hasHeightForWidth())
        self.Num1.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num1.setFont(font)
        self.Num1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num1.setToolTip("")
        self.Num1.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num1.setObjectName("Num1")
        self.GridNumbers.addWidget(self.Num1, 2, 0, 1, 1)
        self.Num5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num5.sizePolicy().hasHeightForWidth())
        self.Num5.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num5.setFont(font)
        self.Num5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num5.setToolTip("")
        self.Num5.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num5.setObjectName("Num5")
        self.GridNumbers.addWidget(self.Num5, 1, 1, 1, 1)
        self.SqrBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SqrBtn.sizePolicy().hasHeightForWidth())
        self.SqrBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.SqrBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.SqrBtn.setFont(font)
        self.SqrBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.SqrBtn.setToolTip("Root")
        self.SqrBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.SqrBtn.setObjectName("SqrBtn")
        self.GridNumbers.addWidget(self.SqrBtn, 2, 6, 1, 1)
        self.Num0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num0.sizePolicy().hasHeightForWidth())
        self.Num0.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num0.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num0.setFont(font)
        self.Num0.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num0.setToolTip("")
        self.Num0.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num0.setAutoDefault(False)
        self.Num0.setDefault(False)
        self.Num0.setFlat(False)
        self.Num0.setObjectName("Num0")
        self.GridNumbers.addWidget(self.Num0, 3, 1, 1, 1)
        self.Num3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num3.sizePolicy().hasHeightForWidth())
        self.Num3.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num3.setFont(font)
        self.Num3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num3.setToolTip("")
        self.Num3.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num3.setObjectName("Num3")
        self.GridNumbers.addWidget(self.Num3, 2, 2, 1, 1)
        self.PowBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PowBtn.sizePolicy().hasHeightForWidth())
        self.PowBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PowBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.PowBtn.setFont(font)
        self.PowBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PowBtn.setToolTip("Power")
        self.PowBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.PowBtn.setObjectName("PowBtn")
        self.GridNumbers.addWidget(self.PowBtn, 1, 6, 1, 1)
        self.FacBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FacBtn.sizePolicy().hasHeightForWidth())
        self.FacBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.FacBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.FacBtn.setFont(font)
        self.FacBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.FacBtn.setToolTip("Factorial")
        self.FacBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.FacBtn.setObjectName("FacBtn")
        self.GridNumbers.addWidget(self.FacBtn, 3, 6, 1, 1)
        self.Num2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num2.sizePolicy().hasHeightForWidth())
        self.Num2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num2.setFont(font)
        self.Num2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num2.setToolTip("")
        self.Num2.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num2.setObjectName("Num2")
        self.GridNumbers.addWidget(self.Num2, 2, 1, 1, 1)
        self.EqualBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EqualBtn.sizePolicy().hasHeightForWidth())
        self.EqualBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.EqualBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.EqualBtn.setFont(font)
        self.EqualBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EqualBtn.setToolTip("")
        self.EqualBtn.setStyleSheet("background-color: rgb(0,160,0)")
        self.EqualBtn.setObjectName("EqualBtn")
        self.GridNumbers.addWidget(self.EqualBtn, 3, 7, 1, 1)
        self.BackspaceBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackspaceBtn.sizePolicy().hasHeightForWidth())
        self.BackspaceBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.BackspaceBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setKerning(False)
        self.BackspaceBtn.setFont(font)
        self.BackspaceBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.BackspaceBtn.setToolTip("Backspace")
        self.BackspaceBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.BackspaceBtn.setText("⌫")
        self.BackspaceBtn.setObjectName("BackspaceBtn")
        self.GridNumbers.addWidget(self.BackspaceBtn, 0, 6, 1, 1)
        self.Num8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Num8.sizePolicy().hasHeightForWidth())
        self.Num8.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Num8.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.Num8.setFont(font)
        self.Num8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Num8.setToolTip("")
        self.Num8.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.Num8.setObjectName("Num8")
        self.GridNumbers.addWidget(self.Num8, 0, 1, 1, 1)
        self.AnsBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnsBtn.sizePolicy().hasHeightForWidth())
        self.AnsBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.AnsBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.AnsBtn.setFont(font)
        self.AnsBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.AnsBtn.setToolTip("Return result to input line")
        self.AnsBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.AnsBtn.setObjectName("AnsBtn")
        self.GridNumbers.addWidget(self.AnsBtn, 3, 2, 1, 1)
        self.CommaBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CommaBtn.sizePolicy().hasHeightForWidth())
        self.CommaBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.CommaBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.CommaBtn.setFont(font)
        self.CommaBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CommaBtn.setToolTip("")
        self.CommaBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.CommaBtn.setObjectName("CommaBtn")
        self.GridNumbers.addWidget(self.CommaBtn, 3, 0, 1, 1)
        self.LnBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LnBtn.sizePolicy().hasHeightForWidth())
        self.LnBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.LnBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.LnBtn.setFont(font)
        self.LnBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.LnBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.LnBtn.setObjectName("LnBtn")
        self.GridNumbers.addWidget(self.LnBtn, 1, 7, 1, 1)
        self.PiBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PiBtn.sizePolicy().hasHeightForWidth())
        self.PiBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PiBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.PiBtn.setFont(font)
        self.PiBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PiBtn.setToolTip("Pi")
        self.PiBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.PiBtn.setObjectName("PiBtn")
        self.GridNumbers.addWidget(self.PiBtn, 2, 7, 1, 1)
        self.PlusBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlusBtn.sizePolicy().hasHeightForWidth())
        self.PlusBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PlusBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.PlusBtn.setFont(font)
        self.PlusBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PlusBtn.setToolTip("")
        self.PlusBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.PlusBtn.setObjectName("PlusBtn")
        self.GridNumbers.addWidget(self.PlusBtn, 2, 5, 1, 1)
        self.DivBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DivBtn.sizePolicy().hasHeightForWidth())
        self.DivBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.DivBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.DivBtn.setFont(font)
        self.DivBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.DivBtn.setToolTip("")
        self.DivBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.DivBtn.setObjectName("DivBtn")
        self.GridNumbers.addWidget(self.DivBtn, 1, 5, 1, 1)
        self.ClearBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearBtn.sizePolicy().hasHeightForWidth())
        self.ClearBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.ClearBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.ClearBtn.setFont(font)
        self.ClearBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ClearBtn.setToolTip("Clear input")
        self.ClearBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.ClearBtn.setObjectName("ClearBtn")
        self.GridNumbers.addWidget(self.ClearBtn, 0, 7, 1, 1)
        self.MinusBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinusBtn.sizePolicy().hasHeightForWidth())
        self.MinusBtn.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.MinusBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setKerning(False)
        self.MinusBtn.setFont(font)
        self.MinusBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MinusBtn.setToolTip("")
        self.MinusBtn.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.MinusBtn.setObjectName("MinusBtn")
        self.GridNumbers.addWidget(self.MinusBtn, 3, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.GridNumbers.addItem(spacerItem, 0, 4, 1, 1)
        self.lineInput = QtWidgets.QLineEdit(self.centralwidget)
        self.lineInput.setGeometry(QtCore.QRect(0, 138, 631, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.lineInput.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lineInput.setFont(font)
        self.lineInput.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.lineInput.setFrame(False)
        self.lineInput.setPlaceholderText("10+5")
        self.lineInput.setObjectName("lineInput")
        self.textDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.textDisplay.setGeometry(QtCore.QRect(1, 0, 631, 134))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.textDisplay.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textDisplay.setFont(font)
        self.textDisplay.setMouseTracking(False)
        self.textDisplay.setAutoFillBackground(False)
        self.textDisplay.setStyleSheet("font: 15pt \"Calibri\";\n"
"background-color: rgb(72, 72, 72);\n"
"color:white;\n"
"")
        self.textDisplay.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.textDisplay.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textDisplay.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textDisplay.setOpenLinks(True)
        self.textDisplay.setObjectName("textDisplay")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-20, 130, 691, 10))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-20, 178, 691, 10))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.delHistoryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delHistoryBtn.setGeometry(QtCore.QRect(570, 10, 31, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.delHistoryBtn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.delHistoryBtn.setFont(font)
        self.delHistoryBtn.setObjectName("delHistoryBtn")
        calculator.setCentralWidget(self.centralwidget)

        #attachment of buttons and keys to functions
        self.Num0.clicked.connect(lambda: (self.addSymbolToInput(0)))
        self.Num1.clicked.connect(lambda: (self.addSymbolToInput(1)))
        self.Num2.clicked.connect(lambda: (self.addSymbolToInput(2)))
        self.Num3.clicked.connect(lambda: (self.addSymbolToInput(3)))
        self.Num4.clicked.connect(lambda: (self.addSymbolToInput(4)))
        self.Num5.clicked.connect(lambda: (self.addSymbolToInput(5)))
        self.Num6.clicked.connect(lambda: (self.addSymbolToInput(6)))
        self.Num7.clicked.connect(lambda: (self.addSymbolToInput(7)))
        self.Num8.clicked.connect(lambda: (self.addSymbolToInput(8)))
        self.Num9.clicked.connect(lambda: (self.addSymbolToInput(9)))
        self.PlusBtn.clicked.connect(lambda: (self.addSymbolToInput("+")))
        self.DivBtn.clicked.connect(lambda: (self.addSymbolToInput("/")))
        self.MultiplyBtn.clicked.connect(lambda: (self.addSymbolToInput("x")))
        self.MinusBtn.clicked.connect(lambda: (self.addSymbolToInput("-")))
        self.CommaBtn.clicked.connect(lambda: (self.addSymbolToInput(".")))
        self.FacBtn.clicked.connect(lambda: (self.addSymbolToInput("!")))
        self.PowBtn.clicked.connect(lambda: (self.addSymbolToInput("^")))
        self.SqrBtn.clicked.connect(lambda: (self.addSymbolToInput("√")))
        self.PiBtn.clicked.connect(lambda: (self.addSymbolToInput("π")))
        self.LnBtn.clicked.connect(lambda: (self.addSymbolToInput("ln")))
        self.delHistoryBtn.clicked.connect(self.delHistory)
        self.ClearBtn.clicked.connect(self.clear)
        self.BackspaceBtn.clicked.connect(self.backspace)
        self.EqualBtn.clicked.connect(self.calculate)
        self.AnsBtn.clicked.connect(self.ansToInput)
        keyboard.on_press_key("Enter", self.calculate)

        #init setup
        self.res = ""
        self.lineInput.setFocus()

        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "Calculator"))
        self.Num7.setText(_translate("calculator", "7"))
        self.MultiplyBtn.setText(_translate("calculator", "×"))
        self.Num9.setText(_translate("calculator", "9"))
        self.Num4.setText(_translate("calculator", "4"))
        self.Num6.setText(_translate("calculator", "6"))
        self.Num1.setText(_translate("calculator", "1"))
        self.Num5.setText(_translate("calculator", "5"))
        self.SqrBtn.setText(_translate("calculator", "n√x"))
        self.Num0.setText(_translate("calculator", "0"))
        self.Num3.setText(_translate("calculator", "3"))
        self.PowBtn.setText(_translate("calculator", "x^n"))
        self.FacBtn.setText(_translate("calculator", "x!"))
        self.Num2.setText(_translate("calculator", "2"))
        self.EqualBtn.setText(_translate("calculator", "="))
        self.Num8.setText(_translate("calculator", "8"))
        self.AnsBtn.setText(_translate("calculator", "Ans"))
        self.CommaBtn.setText(_translate("calculator", "."))
        self.LnBtn.setText(_translate("calculator", "ln x"))
        self.PiBtn.setText(_translate("calculator", "π"))
        self.PlusBtn.setText(_translate("calculator", "+"))
        self.DivBtn.setText(_translate("calculator", "/"))
        self.ClearBtn.setText(_translate("calculator", "C"))
        self.MinusBtn.setText(_translate("calculator", "-"))
        self.delHistoryBtn.setToolTip(_translate("calculator", "Delete history"))
        self.delHistoryBtn.setText(_translate("calculator", "DEL"))
        self.textDisplay.setHtml(_translate("calculator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"UTF-8\"><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


    def addSymbolToInput(self, num):
        curText = self.lineInput.text()
        cursorPos = self.lineInput.cursorPosition()

        curText = curText[0:cursorPos] + str(num) + curText[cursorPos:]
        self.lineInput.setText(curText)
        self.lineInput.setFocus()
        self.lineInput.setCursorPosition(cursorPos + len(str(num)))

    def clear(self):
        self.lineInput.setText("")
        self.lineInput.setFocus()

    def backspace(self):
        curText = self.lineInput.text()
        if len(curText) == 0:
            return

        cursorPos = self.lineInput.cursorPosition()-1
        #if char is not alphabet, erase and return
        if not curText[cursorPos-1].isalpha():
            self.lineInput.setText(curText[0 : cursorPos : ] + curText[cursorPos + 1 : :])
            self.lineInput.setFocus()
            self.lineInput.setCursorPosition(cursorPos)
            return

        #erase while current char is alphabet
        while len(self.lineInput.text()):
            curText = self.lineInput.text()
            if not curText[cursorPos].isalpha():
                break
            self.lineInput.setText(curText[0 : cursorPos : ] + curText[cursorPos + 1 : :])
            #self.lineInput.setFocus()
            cursorPos-=1
        self.lineInput.setFocus()
        self.lineInput.setCursorPosition(cursorPos+1)
        

    def ansToInput(self):
        curText = self.lineInput.text()
        self.lineInput.setText(curText + str(self.res))
        self.lineInput.setFocus()

    def delHistory(self):
        self.textDisplay.clear()
        self.lineInput.setFocus()

    def splitExprToArr(self, expression):
            expArr = re.split(r'(\+|-|x|/|!|\^|√|π|ln)', expression)
            
            for i in expArr:
                if i == '':
                    expArr.remove('')

            for index,i in enumerate(expArr):
                if re.fullmatch(r'(\+|-|x|\*|/)',expArr[index]) and index == 0:
                    expArr.insert(0,"0")
                elif (i == "-" or i == "+") and re.fullmatch(r'(x|/|^|ln)',expArr[index-1]):
                    expArr[index] = str(expArr[index]) + str(expArr.pop(index+1))
                elif (i == "√" or i == "^") and (index == 0 or re.fullmatch(r'(x|\*|/|\+|-)',expArr[index-1])):
                    expArr.insert(index,"2")
                elif (i == "!") and (index == 0 or re.fullmatch(r'(x|\*|/|\+|-)',expArr[index-1])):
                    expArr.pop(index)
                    
            return expArr

    def calculate(self,key):
        try:
            expression = self.lineInput.text()
            expArr = self.splitExprToArr(expression)
            if len(expArr) == 0:
                self.lineInput.setFocus()
                return

            expr = ""
            indexesToRemove = []

            #process operations with highest priority
            for index,i in enumerate(expArr):   
                if i == "π":
                    expr = 'calcLib.pi()'
                    expArr[index] = expr
                    if not len(expArr)-index-1 == 0 and not re.match(r'(\+|-|x|/|!|\^)',expArr[index+1]):
                        expArr.insert(index+1,"x")
                    if index > 0 and not re.fullmatch(r'(\+|-|x|/|!|\^)',expArr[index-1]):
                        expArr.insert(index,"x")

            print(expArr)##############################################debug
            #process operations with 2nd highest priority
            for index,i in enumerate(expArr):
                for opearation in ["!","^","√","ln"]:    
                    if i == opearation:

                        if i == "ln":
                            operand2 = expArr[index+1]
                            expr = 'calcLib.ln('+operand2+')'
                            expArr[index+1] = expr
                            indexesToRemove.insert(0,index)
                            if index > 0 and not re.match(r'(\+|-|x|/|!|\^)',expArr[index-1]):
                                expArr.insert(index+1,"x")
                            break

                        operand = expArr[index-1]

                        if i == "!":
                            expr = 'calcLib.fac('+operand+')'
                            expArr[index] = expr
                            indexesToRemove.insert(0,index-1)

                        elif i == "^":    
                            operand2 = expArr[index+1]
                            expr = 'calcLib.pwr('+operand+','+operand2+')'
                            expArr[index+1] = expr
                            indexesToRemove.insert(0,index-1)
                            indexesToRemove.insert(0,index)
                        elif i == "√":
                            operand2 = expArr[index+1]
                            expr = 'calcLib.root('+operand2+','+operand+')'
                            expArr[index+1] = expr
                            indexesToRemove.insert(0,index-1)
                            indexesToRemove.insert(0,index)
            for index in indexesToRemove:
                expArr.pop(int(index))
            indexesToRemove.clear()
            
            #process operations with 3nd highest priority
            for index,i in enumerate(expArr):
                for operation in ["x","*","/"]:
                    if i == operation:
                        operand = expArr[index-1]
                        operand2 = expArr[index+1]
                        if i == "x" or i == "*":
                            expr = 'calcLib.mul('+operand+','+operand2+')'
                            expArr[index+1] = expr
                        else:
                            expr = 'calcLib.div('+operand+','+operand2+')'
                            expArr[index+1] = expr
                        indexesToRemove.insert(0,index-1)
                        indexesToRemove.insert(0,index)

            for index in indexesToRemove:
                expArr.pop(int(index))
            indexesToRemove.clear()

            #process operations with 4rd highest priority
            for index,i in enumerate(expArr):
                for operation in ["+","-"]:
                    if i == operation:
                        operand = expArr[index-1]
                        operand2 = expArr[index+1]
                        if i == "+":
                            expr = 'calcLib.add('+operand+','+operand2+')'
                            expArr[index+1] = expr
                        else:
                            expr = 'calcLib.sub('+operand+','+operand2+')'
                            expArr[index+1] = expr
                        indexesToRemove.insert(0,index-1)
                        indexesToRemove.insert(0,index)

            for index in indexesToRemove:
                expArr.pop(int(index))
            indexesToRemove.clear()
                

            print(expArr)##############################################debug
            print(expr)##############################################debug
            self.res = eval(expr)  
        except:
            #print(expArr)######################################################################################debug
            self.res="Wrong input!"

        self.textDisplay.append(str(expression) + '        =       ' + str(self.res))
        self.textDisplay.ensureCursorVisible()
        self.lineInput.setFocus()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calculator = QtWidgets.QMainWindow()
    ui = Ui_calculator()
    ui.setupUi(calculator)
    calculator.show()
    sys.exit(app.exec_())